import{state}from'./state.js';import{saveSettings}from'./settings.js';import{showModal}from'./components/modal.js';import{showToast}from'./components/toast.js';import{escapeHTML,todayISO}from'./utils.js';import{icon}from'./components/icons.js';
const DEFAULT_PHOTO='assets/image/aldo.png';
export const profilePhoto=()=>state.data.settings.profilePhoto||DEFAULT_PHOTO;
function ageOn(date){const birth=new Date(`${date}T00:00:00`),now=new Date();let age=now.getFullYear()-birth.getFullYear();if(now<new Date(now.getFullYear(),birth.getMonth(),birth.getDate()))age--;return age}
function smartInsight(){const s=state.data.settings,today=todayISO(),events=state.data.events.filter(e=>e.date===today).length,open=state.data.tasks.filter(t=>t.status!=='completed'),overdue=open.filter(t=>t.dueDate&&t.dueDate<today).length;if(s.birthDate&&s.birthDate.slice(5)===today.slice(5))return`Happy birthday! You are ${ageOn(s.birthDate)} today. Make it a meaningful one.`;if(overdue)return`${overdue} overdue ${overdue===1?'task needs':'tasks need'} your attention first.`;if(events)return`You have ${events} ${events===1?'event':'events'} today. Your next move is already mapped out.`;if(open.length)return`${open.length} open ${open.length===1?'task':'tasks'} — choose one small win to start.`;return'Your board is clear. A good moment to plan what matters next.'}
export function syncProfileUI(){const img=document.querySelector('#profile-avatar');if(img)img.src=profilePhoto()}
export function enhanceDashboard(){const header=document.querySelector('#main-content .page > header');if(!header)return;const s=state.data.settings,name=s.firstName?.trim()||'there',safeName=escapeHTML(name),heading=header.querySelector('h2');if(heading)heading.textContent=`Hello, ${name}`;header.classList.add('home-hero');header.insertAdjacentHTML('afterbegin',`<img class="home-avatar" src="${profilePhoto()}" alt="${safeName}'s profile photo">`);header.insertAdjacentHTML('beforeend',`<div class="smart-insight"><span>${icon('spark',18)}</span><p>${smartInsight()}</p></div>`)}
export function openProfileEditor(){const s=state.data.settings,f=document.createElement('form');f.className='form-grid';f.innerHTML=`<div class="profile-preview"><img src="${profilePhoto()}" alt="Profile preview"><div><strong>${escapeHTML(s.firstName||'Aldo')}</strong><small>Stored locally on this device</small></div></div><div class="field"><label>First name</label><input class="input" name="firstName" maxlength="40" value="${escapeHTML(s.firstName||'')}"></div><div class="field"><label>Date of birth</label><input class="input" name="birthDate" type="date" value="${s.birthDate||'2004-04-12'}"></div><div class="field"><label>Profile photo</label><input class="input" name="photo" type="file" accept="image/png,image/jpeg,image/webp"><small>Choose a photo up to 2 MB. It stays in this browser.</small></div>`;let photo=s.profilePhoto||'';f.elements.photo.onchange=()=>{const file=f.elements.photo.files[0];if(!file)return;if(file.size>2_000_000||!['image/png','image/jpeg','image/webp'].includes(file.type)){showToast('Choose a PNG, JPEG, or WebP image smaller than 2 MB.','error');f.elements.photo.value='';return}const reader=new FileReader();reader.onload=()=>{photo=reader.result;f.querySelector('.profile-preview img').src=photo};reader.readAsDataURL(file)};showModal({title:'Edit profile',content:f,actions:[{label:'Cancel',className:'ghost',value:false},{label:'Save profile',onClick:async({close})=>{await saveSettings({firstName:f.elements.firstName.value.trim(),birthDate:f.elements.birthDate.value,profilePhoto:photo});syncProfileUI();close(true);showToast('Profile updated.');location.hash='#/dashboard'}}]})}
export function enhanceSettings(){const first=document.querySelector('#main-content .card');if(!first||document.querySelector('[data-edit-profile]'))return;first.insertAdjacentHTML('afterbegin',`<div class="profile-preview"><img src="${profilePhoto()}" alt="Profile photo"><div><strong>${escapeHTML(state.data.settings.firstName||'Aldo')}</strong><small>${state.data.settings.birthDate||'2004-04-12'}</small></div><button class="button secondary small" data-edit-profile>Edit profile</button></div>`);first.querySelector('[data-edit-profile]').onclick=openProfileEditor}
